package quiz

const (
	BadBank           = "Некорректный банк вопросов"
	NoQuestions       = "В комнате нет вопросов"
	HostEditsBank     = "Только ведущий меняет вопросы"
	BankBeforeStart   = "Вопросы можно менять до старта"
	HostPicksChooser  = "Первого игрока выбирает ведущий"
	ChooserLocked     = "Сейчас нельзя сменить того, кто выбирает"
	ChooserRequired   = "Сначала ведущий выбирает, кто ходит первым"
	OtherPlayersTurn  = "Сейчас выбирает другой игрок"
	QuestionPlayed    = "Этот вопрос уже сыгран"
	QuestionMissing   = "Вопрос не найден"
	HostBackToBoard   = "Только ведущий возвращает поле"
	HostSkipOnly      = "Сдать вопрос может только ведущий"
	HostRevealOnly    = "Вскрыть ответы может только ведущий"
	NoOpenQuestion    = "Сейчас нет открытого вопроса"
	UnknownMessage    = "Неизвестное сообщение викторины"
	WrongQuestion     = "Сейчас нет этого вопроса"
	AlreadyRevealed   = "Ответы уже вскрыты"
	HostDoesNotAnswer = "Ведущий не отвечает на вопросы"
	AlreadyAnswered   = "Вы уже ответили"
	EnterAnswer       = "Введите ответ"
	PickAnswer        = "Выберите вариант"
	PickOneAnswer     = "Выберите один вариант"
	CannotPickAll     = "Все варианты выбрать нельзя"
	AnswerMissing     = "Ответ не найден"
	HostAwards        = "Очки начисляет ведущий"
	WaitForAnswers    = "Сначала дождитесь всех ответов"
	AlreadyAwarded    = "Очки уже начислены"
	NotFreeQuestion   = "Это не свободный вопрос"
	BadState          = "Некорректное состояние викторины"
)
