export interface DeepQuestion {
  id: string
  title: string
}

const TITLES = [
  'What would you change about yourself if you could?',
  'What motivates you to work hard?',
  'What form of public transportation do you prefer, and why? (air, boat, train, bus, taxi, etc.)',
  'What’s the most spontaneous thing you’ve done lately?',
  'What two radio stations do you listen to in the car the most, and why?',
  'If you could hire someone to help you, would it be with cleaning, cooking or yard work?',
  'Would you rather vacation in Mexico or Alaska, and why?',
  'What is your favorite thing about your career?',
  'If you could live anywhere, where would it be?',
  'Who is your hero?',
  'What is your family member’s proudest accomplishment?',
  'What is your favorite book to read?',
  'What are your hobbies?',
  'What is your biggest fear?',
  'If you could choose to do anything for a day, what would it be?',
  'What is the best gift you have been given?',
  'What really makes you angry?',
  'If you could choose to do anything for a day, what would it be?',
  'Would you rather win the lottery or work at the perfect job? And why?',
  'Have you ever had a nickname? What is it?',
  'What would you do if you won the lottery?',
  'Do you like or dislike surprises? Why or why not?',
  'Would you rather ride a bike, ride a horse or drive a car?',
  'In the evening, would you rather play a game, visit a relative, watch a movie or read?',
  'What is your favorite game or sport to watch and play?',
  'If you could only eat one meal for the rest of your life, what would it be?',
  'Who is your favorite author?',
  'What is your favorite family vacation?',
  'What is your biggest complaint about your job?',
  'Which would you rather do: wash dishes, mow the lawn, clean the bathroom or vacuum the house?',
  'What is your proudest accomplishment?',
  'Would you rather win the lottery or work at the perfect job? And why?',
  'What’s your favorite zoo animal, and why?',
  'What makes you laugh the most?',
  'Who would you want to be stranded with on a deserted island?',
  'If you could go back in time to change one thing, what would it be?',
  'If you could share a meal with any four individuals, living or dead, who would they be?',
  'How many pillows and blankets do you have to sleep with?',
  'What’s the longest you’ve gone without sleep (and why)?',
  'What’s the tallest building you’ve been to the top in, and how did it make you feel?',
  'What was the last movie you went to? What did you think?',
  'What did you want to be when you were small?',
  'Where do you see yourself in five years?',
  'If you were a superhero, what powers would you have?',
  'If money was no object, what would you do all day?',
  'If you could go back in time, what year would you travel to?',
  'What are two of your biggest pet peeves?',
  'Aside from necessities, what one thing could you not go a day without?',
  'How would your friends describe you?',
  'What would you sing at karaoke night, and why?',
  'What is the worst gift you have received?',
  'What’s the emoji you use the most? And why do you think that is?',
  'What are your three favorite TV shows of all time?',
  'What fictional character do you most identify with?',
  'Do you have the desire to be famous?',
  'What unnecessary products or services do you consider necessary?',
  'Which fictional villain made you feel real hatred towards them?',
  'What habit do you have that you think not many other people have?',
  'How often is your brain on autopilot?',
  'How long have you gone without talking to a family member?',
  'If colors had a taste, what would each color taste like?',
  'What names were ruined for you because you knew someone terrible with that name?',
  'What’s the best conspiracy theory you can think of?',
  'How often do you feel utterly worn down?',
  'What gross and unhygienic things do people do that bother you?',
  'What was the best thing about how your parents raised you?',
  'Where is the craziest place you have danced, and how did it make you feel?',
  'If when you died, you got put into a room for eternity with people who died the same way, how would you want to die?',
  'What would an amusement park filled with your biggest fears be like? What rides would it have?',
  'If there was a slogan for your life, what would it be?',
  'What do you think people really need to chill out about?',
  'What are the two biggest lessons you’ve learned from previous relationships?',
  'Why do you think we dream?',
  'If you could switch bodies for a length of time of your choosing, would you? And if so, how long?',
  'What inedible thing do you wish you could eat?',
  'Which hairstyles fit with which personalities?',
  'If you could choose the next president of the United States, who would it be?',
  'What’s the most stress-relieving thing you can get/do for less than $20?',
  'What’s something you wish you had never learned how it was made or how it works?',
  'What do most people overestimate or underestimate about you?',
  'What silly thing do you take a lot of pride in?',
  'What crazy things will you do if you ever become rich?',
  'If you were forced into a dance competition, what song would you choose to dance to, and why?',
  'You have unlimited wishes but every time you make a wish, what you love most is erased from the world. How many wishes do you make and what do you wish for? (No, you can’t wish not to have things erased from the world.)',
  'How do you think the world should change?',
  'How do you feel about God?',
  'What scrambles your brain every time you think about it?',
  'Do you think social media is good or bad for our society?',
  'What would be the absolute perfect day?',
  'Is there a movie that you think every person should watch in their lifetime?',
  'If you could change your first name, what do you wish it would be?',
  'What do you think aliens would look/be like?',
  'How often do you think about death?',
  'Are there any medical concerns that run in your family?',
  'Are you happy with how you were raised?',
  'What event from the past do you most want to see a recording of?',
  'What would an amusement park designed specifically to make you happy, be like?',
  'What is something you probably should do, but will never do?',
  'What great idea would you like to try if you had enough money?',
  'If you were in a high-speed chase, what song would you want blaring on the radio, and why?',
  'Is there a type of music genre that you feel especially connected to?',
  'What is your favorite quote, and why?',
  'If you were given immortality, but there was one condition, what would stop you from accepting immortality?',
  'Do you like or dislike surprises? Why or why not?',
  'What are your favorite books?',
  'Are you a morning person or a night owl?',
  'Are you still friends with anyone from high school?',
  'Who or what inspires you?',
  'If you could be someone else for a day, who would it be and why?',
  'What’s your biggest guilty pleasure?',
  'What celebrity do people compare you to?',
  'Do you believe in soulmates?',
  'What’s the craziest thing you’ve ever done for a friend?',
  'Do you consider yourself a pessimist or an optimist?',
  'Do you think there’s a right age to get married?',
  'What was your best birthday?',
  'Would you rather go on a road trip or take a long flight, and why?',
  'Have you ever seen a ghost?',
  'Do you consider yourself an introvert or an extrovert?',
  'What are you most thankful for?',
  'Which parent are you closer to and why?',
  'What are your thoughts on online dating or apps like Tinder?',
  'What’s on your bucket list this year?',
  'How would you describe your best friend?',
  'What do you think of best friends of the opposite sex?',
  'What makes you feel accomplished?',
  'How do you feel about sharing your password with your partner?',
  'What was the best phase in your life?',
  'Would you still love your spouse if they were diagnosed with a terminal disease?',
  'What qualities do you admire about your parents?',
  'What are some of your favorite songs?',
  'What was the worst phase in your life?',
  'What is the craziest thing you’ve ever done and would you do it again?',
  'If a genie granted you three wishes right now, what would you wish for?',
  'Does your job make you happy?',
  'What’s the one thing you would like to change about yourself?',
  'Would you ever take back someone who cheated?',
  'What is a relationship deal breaker for you?',
  'Are you more into looks or brains?',
  'When do you think a person is ready for marriage?',
  'Is what you’re doing now what you always wanted to do growing up?',
  'Have you ever lost someone close to you?',
  'If you are in a bad mood, do you prefer to be left alone or have someone to cheer you up?',
  'What’s the one thing that people always misunderstand about you?',
  'What is your idea of a perfect vacation, and why?',
  'When was the last time you broke someone’s heart?',
  'Would you relocate for love?',
  'What did you want to be when you were younger?',
  'What kind of parent do you think you will be?',
  'Do you judge a book by its cover?',
  'What’s your biggest regret in life?',
  'Who is that one person you can talk to about just anything?',
  'What’s an ideal weekend for you?',
  'Are you religious or spiritual?',
  'Would you take on your significant other’s religion if they had one?',
  'Do you believe in second chances?',
  'What’s been your biggest mistake so far in life and what did you learn from it?',
  'Where is your favorite place in the entire world to go?',
  'What did your past relationship teach you?',
  'What’s your philosophy in life?',
  'What are your top five favorite movies, and why?',
  'What would you do if your parents didn’t like your partner?',
  'Do you think of yourself as empathetic?',
  'What do you think is the meaning of life?',
  'When have you felt your biggest adrenaline rush?',
  'Why did your last relationship end?',
  'Are you confrontational?',
  'Do you usually stay friends with your exes?',
  'Do you believe in karma?',
  'If you could be a trade sexes for a day, what would you do?',
  'What’s your “and then it got worse” story?',
  'What’s the best piece of advice someone has given you?',
  'What’s something you learned recently that you really should have already known?',
  'What was something you enjoyed as a child but now cringe at the thought of? Can you pinpoint why that changed?',
  'Do you feel a lot of pressure to be successful?',
  'What’s the craziest thing you’ve ever done for love?',
  'Do you prefer being warmed when you’re too cold or being cooled when you’re too hot?',
  'Do you still think about your ex-BFF?',
  'Is flirting cheating?',
  'Would you consider yourself a generous person?',
  'What qualities did you inherit from your parents?',
  'What do you most look forward to about getting old?',
  'Are you passionate about collecting anything?',
  'Are you ever insecure about your sense of humor?',
  'Do you feel more comfortable with the idea of working remotely or in person, and why?',
  'Do you feel understood by the people closest to you?',
  'What do you wish you could re-live in your lifetime?',
  'What’s an innocent mistake you made that had dramatic consequences?',
  'Who would you trust to buy clothes for you and totally nail it?',
  'What’s something weird that you recommend everyone try at least once?',
  'Do you feel a special connection with any particular type of animal?',
  'What are you most grateful for?',
  'Is it hard for you to accept feedback?',
  'Would you go through a boyfriend’s phone if you could?',
  'What’s something horrible that we as humans have accepted, because that’s just how things are; but actually things don’t have to be that way at all?',
  'If you could hear every time someone said something good about you or something negative about you, which would you choose?',
  'What do you think people automatically assume about you when they look at you?',
  'Looking back on your life, what have you done that has given you the most satisfaction?',
  'What’s the best advice you’ve ever gotten?',
  'When was the last time you laughed so hard you cried?',
  'What would you do if your parents didn’t like your partner?',
  'Is there anything you’ve been wanting to tell a friend, but don’t know how to?',
  'What’s your story?',
  'What do you wish you had more time for?',
  'What do you like to do that is traditionally considered masculine?',
  'If everything was quantified, what life stats would like to see for yourself?',
  'What do you really wish you knew when you were younger?',
  'What options would come up if you could “right-click” people?',
  'Do you feel like you’re living out your personal dreams?',
  'What would you do if you weren’t afraid to try?',
  'Would you say you struggle with materialism at all?',
  'When was the last time you had a gut feeling about something that turned out to be correct? How about a time your gut feeling was wrong?',
  'How decisive or indecisive are you?',
  'What’s the biggest lie that you’ve told someone?',
  'What would you do if one day you woke up and every person was just gone without a trace?',
  'What body features do you pay the most attention to?',
  'Do you practice self-affirmations?',
  'Are you trying to “break the cycle” on any family dynamics?',
  'If you could dedicate your life to solving one problem, what problem would you choose?',
  'What was the worst phase you went through in life?',
  'Has anyone ever “mansplained” to you?',
  'What’s the best bad decision you',
  'What’s on your bucket list this year?',
  'Are you close with your family?',
  'What kind of grandparent do you think you will be?',
  'How do you feel about sharing your password with your partner?',
  'What is the craziest thing you’ve ever done and would you do it again?',
  'If you could make one wish right now, what would you wish for?',
  'What’s your biggest regret in life?',
  'What jobs exist because people are selfish?',
  'What do you think about when you’re by yourself?',
  'What is one dream you have yet to accomplish?',
  'Do you think you judge people too harshly sometimes?',
  'What’s the one thing that people always misunderstand about you?',
  'Are you confrontational?',
  'If you could change one thing about yourself what would it be?',
  'What makes you feel accomplished?',
  'When was the last time you broke someone’s heart?',
  'What is your most irrational fear?',
  'Who was your favorite teacher, and why?',
  'If you had to talk about one topic for 10 minutes straight, what would it be?',
  'Would you relocate for love?',
  'What’s your philosophy in life?',
  'When do you think a person is ready for marriage?',
  'What accomplishment are you most proud of?',
  'What’s your favorite hobby to do alone?',
  'Did you ever write a journal?',
  'Is what you’re doing now what you always wanted to do growing up?',
  'What did your past relationship teach you?',
  'What are your thoughts on dating apps?',
  'Which parent are you more like, and why?',
  'What was the best phase in your life?',
  'What are three things you value most about a person?',
  'Who are the five people you are closest with?',
  'Do you believe in second chances?',
  'Who is that one person you can talk to about just anything?',
  'Have you ever lost someone close to you?',
  'If you are in a bad mood, do you prefer to be left alone or have someone to cheer you up?',
  'What’s the most exciting thing that’s happened this past year?',
  'When have you felt your biggest adrenaline rush?',
  'When do you hope to have life figured out?',
  'What’s one thing that bothers you most about the world today?',
  'Do you believe in angel numbers?',
  'Would you ever take back someone who cheated?',
  'What is the greatest struggle you’ve overcome?',
  'Do you consider yourself an introvert or an extrovert?',
  'What’s your favorite book/movie of all time and why did it speak to you so much?',
  'Do you think you put a lot of weight into first impressions?',
  'What’s the one thing you would like to change about yourself?',
  'What would you do if you found out you were adopted?',
  'What if you found out that you were the star of the Truman Show?',
  'What is a relationship deal breaker for you?',
  'What are you most thankful for?',
  'If you were famous, what would you be famous for?',
  'What do you think are the most important qualities of a friend?',
  'When was the last time you cried?',
  'What’s your favorite childhood memory?',
  'Have you ever had your heart broken?',
  'In your opinion, can long-distance relationships ever work?',
  'Have you truly accepted and embraced who you are at your core?',
  'Why is there so much suffering in the world?',
  'What exactly happens when we die?',
  'What is the purpose of my existence?',
] as const

export const DEEP_QUESTIONS: DeepQuestion[] = TITLES.map((title, index) => ({
  id: `deep-question-${index + 1}`,
  title,
}))

/** Stable English dictionary for the future i18n layer. */
export const DEEP_QUESTION_EN: Record<string, string> = Object.fromEntries(
  DEEP_QUESTIONS.map(question => [question.id, question.title]),
)
